#!/bin/sh
ssh ubuntu@ip-10-0-152-225 <<EOF
    cd ~/test-app
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh
    nvm install v10.11.0
    npm install
    sudo npm install -g nodemon pm2
    sudo pm2 restart ecosystem.config.js
    sudo pm2 save
    exit
EOF
